// 勞基法 / 性別平等工作法 全假別主檔
// 對應文件：「綠谷國際_請假制度與勞基法假別規範」
// attachmentRule：REQUIRED 必附 | CONDITIONAL 條件式必附 | FORBIDDEN 不得要求 | OPTIONAL 得要求

export type LeaveCatalogItem = {
  code: string;
  name: string;
  legalBasis: string;
  unit: "HOUR" | "HALF_DAY" | "DAY";
  paidRate: number; // 1 全薪 / 0.5 半薪 / 0 無薪
  annualQuota: number | null; // 日；null = 依規則計算或不設固定額度
  statutoryCap: string | null;
  attachmentRule: "REQUIRED" | "CONDITIONAL" | "FORBIDDEN" | "OPTIONAL";
  attachmentNote: string | null;
  countsAs: string | null;
  deferrable: boolean;
  needsHrReview: boolean;
  sortOrder: number;
};

export const LEAVE_CATALOG: LeaveCatalogItem[] = [
  {
    code: "ANNUAL",
    name: "特別休假",
    legalBasis: "勞基法 §38",
    unit: "HOUR",
    paidRate: 1,
    annualQuota: null,
    statutoryCap: "依年資級距，週年制每滿一年重新給假",
    attachmentRule: "OPTIONAL",
    attachmentNote: null,
    countsAs: null,
    deferrable: true,
    needsHrReview: false,
    sortOrder: 1,
  },
  {
    code: "MARRIAGE",
    name: "婚假",
    legalBasis: "勞工請假規則 §2",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 8,
    statutoryCap: "8 日；結婚登記日前後一定期間內請畢，經同意得於 1 年內分次請",
    attachmentRule: "REQUIRED",
    attachmentNote: "結婚證書 / 戶籍謄本 / 喜帖 擇一",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 2,
  },
  {
    code: "BEREAVEMENT_8",
    name: "喪假（父母、養/繼父母、配偶）",
    legalBasis: "勞工請假規則 §3",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 8,
    statutoryCap: "8 日；事實發生日起 100 日內分次請",
    attachmentRule: "REQUIRED",
    attachmentNote: "死亡證明書 / 除戶戶籍謄本 / 訃聞",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 3,
  },
  {
    code: "BEREAVEMENT_6",
    name: "喪假（祖父母、子女、配偶之父母/養父母/繼父母）",
    legalBasis: "勞工請假規則 §3",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 6,
    statutoryCap: "6 日；事實發生日起 100 日內分次請",
    attachmentRule: "REQUIRED",
    attachmentNote: "死亡證明書 / 除戶戶籍謄本 + 關係證明",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 4,
  },
  {
    code: "BEREAVEMENT_3",
    name: "喪假（曾祖父母、兄弟姊妹、配偶之祖父母）",
    legalBasis: "勞工請假規則 §3",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 3,
    statutoryCap: "3 日；事實發生日起 100 日內分次請",
    attachmentRule: "REQUIRED",
    attachmentNote: "死亡證明書 / 除戶戶籍謄本",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 5,
  },
  {
    code: "SICK",
    name: "普通傷病假（未住院）",
    legalBasis: "勞工請假規則 §4",
    unit: "HOUR",
    paidRate: 0.5,
    annualQuota: 30,
    statutoryCap: "1 年內合計不得逾 30 日；折半發給（勞保傷病給付未達半數者補足）",
    attachmentRule: "CONDITIONAL",
    attachmentNote: "逾 3 日或雇主要求時：醫療機構診斷證明書",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 6,
  },
  {
    code: "SICK_HOSPITAL",
    name: "普通傷病假（住院）",
    legalBasis: "勞工請假規則 §4",
    unit: "DAY",
    paidRate: 0.5,
    annualQuota: 365,
    statutoryCap: "2 年內合計不得逾 1 年（含未住院合併計算）",
    attachmentRule: "REQUIRED",
    attachmentNote: "住院證明、診斷證明書",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 7,
  },
  {
    code: "PREGNANCY_REST",
    name: "安胎休養假",
    legalBasis: "性平法 §15、勞工請假規則 §4",
    unit: "DAY",
    paidRate: 0.5,
    annualQuota: null,
    statutoryCap: "併入病假，但不受 30 日 / 1 年上限限制",
    attachmentRule: "REQUIRED",
    attachmentNote: "醫師診斷證明書（載明需安胎休養及期間）",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 8,
  },
  {
    code: "MENSTRUAL",
    name: "生理假",
    legalBasis: "性別平等工作法 §14",
    unit: "DAY",
    paidRate: 0.5,
    annualQuota: 12,
    statutoryCap: "每月 1 日；全年 3 日不併入病假，逾 3 日部分併入病假；均減半發給",
    attachmentRule: "FORBIDDEN",
    attachmentNote: "不得要求檢附證明文件",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 9,
  },
  {
    code: "MATERNITY",
    name: "產假（分娩）",
    legalBasis: "勞基法 §50",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 56,
    statutoryCap: "8 週（含例假）；受僱滿 6 個月照給、未滿 6 個月折半；應一次請足",
    attachmentRule: "REQUIRED",
    attachmentNote: "嬰兒出生證明或診斷證明書、戶口名簿",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 10,
  },
  {
    code: "MISCARRIAGE_4W",
    name: "產假（妊娠 3 個月以上流產）",
    legalBasis: "勞基法 §50",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 28,
    statutoryCap: "4 週",
    attachmentRule: "REQUIRED",
    attachmentNote: "診斷證明書",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 11,
  },
  {
    code: "MISCARRIAGE_1W",
    name: "產假（妊娠 2–3 個月流產）",
    legalBasis: "勞基法 §50",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 7,
    statutoryCap: "1 週（工資不強制，建議照給）",
    attachmentRule: "REQUIRED",
    attachmentNote: "診斷證明書",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 12,
  },
  {
    code: "MISCARRIAGE_5D",
    name: "產假（妊娠未滿 2 個月流產）",
    legalBasis: "勞基法 §50",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 5,
    statutoryCap: "5 日（工資不強制）",
    attachmentRule: "REQUIRED",
    attachmentNote: "診斷證明書",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 13,
  },
  {
    code: "PRENATAL_CHECKUP",
    name: "產檢假",
    legalBasis: "性平法 §15",
    unit: "HALF_DAY",
    paidRate: 1,
    annualQuota: 7,
    statutoryCap: "7 日；第 6、7 日薪資由政府補助雇主",
    attachmentRule: "REQUIRED",
    attachmentNote: "就診證明文件（產檢紀錄 / 孕婦健康手冊）",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 14,
  },
  {
    code: "PATERNITY",
    name: "陪產檢及陪產假",
    legalBasis: "性平法 §15",
    unit: "HALF_DAY",
    paidRate: 1,
    annualQuota: 7,
    statutoryCap: "7 日；陪產須於分娩當日及前後合計 15 日內請；第 6、7 日政府補助雇主",
    attachmentRule: "REQUIRED",
    attachmentNote: "陪產檢：配偶就診證明；陪產：嬰兒出生證明、戶籍謄本",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 15,
  },
  {
    code: "FAMILY_CARE",
    name: "家庭照顧假",
    legalBasis: "性平法 §20",
    unit: "DAY",
    paidRate: 0,
    annualQuota: 7,
    statutoryCap: "全年 7 日，併入事假計算",
    attachmentRule: "OPTIONAL",
    attachmentNote: "得要求：就診證明、預防接種證明、重大事故證明",
    countsAs: "PERSONAL",
    deferrable: false,
    needsHrReview: false,
    sortOrder: 16,
  },
  {
    code: "PERSONAL",
    name: "事假",
    legalBasis: "勞工請假規則 §7",
    unit: "HOUR",
    paidRate: 0,
    annualQuota: 14,
    statutoryCap: "全年 14 日（含併入之家庭照顧假 7 日）",
    attachmentRule: "OPTIONAL",
    attachmentNote: "敘明理由；必要時檢附證明",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 17,
  },
  {
    code: "OFFICIAL",
    name: "公假",
    legalBasis: "勞工請假規則 §8",
    unit: "HOUR",
    paidRate: 1,
    annualQuota: null,
    statutoryCap: "依法令實際需要",
    attachmentRule: "REQUIRED",
    attachmentNote: "徵集令 / 開庭或作證通知 / 隔離通知書 / 政府開會通知",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 18,
  },
  {
    code: "OCCUPATIONAL",
    name: "公傷病假（職業災害）",
    legalBasis: "勞基法 §59、勞工職業災害保險及保護法",
    unit: "DAY",
    paidRate: 1,
    annualQuota: null,
    statutoryCap: "醫療中不能工作期間，至醫療終止；雇主按原領工資補償",
    attachmentRule: "REQUIRED",
    attachmentNote: "職業傷病診斷書、職災認定文件、勞保職災給付文件",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 19,
  },
  {
    code: "JOB_SEEKING",
    name: "謀職假",
    legalBasis: "勞基法 §16",
    unit: "HOUR",
    paidRate: 1,
    annualQuota: null,
    statutoryCap: "資遣預告期間內，每星期不逾 2 日之工作時間",
    attachmentRule: "REQUIRED",
    attachmentNote: "資遣預告通知書",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 20,
  },
  {
    code: "PARENTAL_UNPAID",
    name: "育嬰留職停薪",
    legalBasis: "性別平等工作法 §16",
    unit: "DAY",
    paidRate: 0,
    annualQuota: null,
    statutoryCap: "子女滿 3 歲前，每一子女最長 2 年；受僱滿 6 個月始得申請；應 10 日前提出",
    attachmentRule: "REQUIRED",
    attachmentNote: "子女出生證明 / 戶籍謄本、書面申請（起訖日、子女資料）",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 21,
  },
  {
    code: "INDIGENOUS_RITUAL",
    name: "原住民族歲時祭儀假",
    legalBasis: "紀念日及節日實施條例",
    unit: "DAY",
    paidRate: 1,
    annualQuota: 1,
    statutoryCap: "1 日，依中央公告之族別祭儀日期",
    attachmentRule: "OPTIONAL",
    attachmentNote: "註記原住民身分之戶籍資料",
    countsAs: null,
    deferrable: false,
    needsHrReview: false,
    sortOrder: 22,
  },
  {
    code: "EPIDEMIC",
    name: "防疫隔離假 / 疫苗接種假",
    legalBasis: "特別條例（視政府公告）",
    unit: "DAY",
    paidRate: 0,
    annualQuota: null,
    statutoryCap: "依當期政府公告；預設停用",
    attachmentRule: "REQUIRED",
    attachmentNote: "隔離 / 檢疫通知書、接種紀錄",
    countsAs: null,
    deferrable: false,
    needsHrReview: true,
    sortOrder: 23,
  },
];

export const ATTACHMENT_RULE_LABEL: Record<string, string> = {
  REQUIRED: "必附（未上傳不可送出）",
  CONDITIONAL: "條件式必附（逾 3 日或 HR 要求）",
  FORBIDDEN: "不得要求（系統不提供附件欄位）",
  OPTIONAL: "得要求（選填）",
};

export const PAID_RATE_LABEL = (r: number) =>
  r >= 1 ? "全薪" : r === 0.5 ? "半薪" : r === 0 ? "無薪" : `${r * 100}%`;
